# **Numpy**

In [2]:
import numpy as np

### Zeroes

In [3]:
ar_zero=np.zeros((5, 4))
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Ones

In [4]:
ar_ones=np.ones((3,4))
print(ar_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Empty

In [5]:
ar_em=np.empty((2,3))
print(ar_em)

#prints values of previous array

[[0. 0. 0.]
 [0. 0. 0.]]


### Range

In [6]:
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


### Random

In [7]:
np.random.rand(5)
#np.random.rand(5, 3)

array([0.38384942, 0.91658443, 0.40515186, 0.00531155, 0.07542098])

In [8]:
np.random.randn(3, 2)

array([[-0.20245089,  0.02088281],
       [ 0.14812012,  1.11923659],
       [ 0.68782878, -1.24923644]])

### Diagonal

In [9]:
ar_dia=np.eye(3, 5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Linspace

In [10]:
ar_lin=np.linspace(1, 20, 4)
print(ar_lin)

[ 1.          7.33333333 13.66666667 20.        ]


### Array multiply
dot product
multiplictaion


In [11]:
kanto=np.array([1, 3.2, 5.2])
weight=np.array([3, 1.3, 42])
np.dot(kanto, weight)

225.56

In [12]:
kanto*weight #element wise multiplication

array([  3.  ,   4.16, 218.4 ])

### Multidimensional array

In [13]:
climate_data=np.array([[23, 24, 53],
                       [35, 34, 64],
                       [47, 57, 23],
                       [23, 46, 65],
                       [13, 45, 76]])
climate_data

array([[23, 24, 53],
       [35, 34, 64],
       [47, 57, 23],
       [23, 46, 65],
       [13, 45, 76]])

In [14]:
climate_data.shape

(5, 3)

matrix multiplication

In [15]:
#np.matmul(climate_data, weight)

climate_data @ weight

array([2326.2, 2837.2, 1181.1, 2858.8, 3289.5])

In [16]:
climate_data1=np.array([[44, 634, 53],
                       [34, 65, 64],
                       [47, 75, 86],
                       [63, 46, 65],
                       [356, 56, 56]])
climate_data2=np.array([[68, 23, 85],
                       [457, 34, 64],
                       [47, 86, 23],
                       [64, 21, 65],
                       [13, 4, 76]])

climate_concat=np.concatenate((climate_data1, climate_data2), axis=1)
climate_concat

array([[ 44, 634,  53,  68,  23,  85],
       [ 34,  65,  64, 457,  34,  64],
       [ 47,  75,  86,  47,  86,  23],
       [ 63,  46,  65,  64,  21,  65],
       [356,  56,  56,  13,   4,  76]])

### stacking vectors

### working with CSV

In [19]:
climate=np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate.shape


(1462, 5)